spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${SBM_CRM_DB_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    show-sql: true
  batch:
    jdbc:
      table-prefix: sbm_crm_
server:
  servlet:
    contextPath: /sbm-crm-api